// Pet.Hosting/App/pages/Index.jsx
﻿import React, { Component } from 'react';
import SearchFrom from './components/SearchFrom.jsx';
import Map from './components/Map.jsx';
import ResultList from './components/ResultList.jsx';

class Index extends Component {
    render() {
        return (
            <div className="container">
                <div className="row">
                    <div className="col-4">
                        <SearchFrom />
                    </div>
                    <div className="col-8">
                        <Map />
                    </div>
                </div>
                <div className="row">
                    <ResultList />
                </div>
            </div>
        );
    }
}

export default Index;

// Pet.Hosting/App/pages/Index.vue
﻿<template>
    <div class="container">
        <div class="row">
            <div class="col-4">
                <search></search>
            </div>
            <div class="col-8">
                <ya-map></ya-map>
            </div>
        </div>
        <div class="row">
            <list></list>
        </div>
    </div>
</template>

<script>
    import Search from '../components/Search.vue'
    import Map from '../components/Map.vue'
    import List from '../components/List.vue'

    export default {
        name: 'index',
        components: {
            'search': Search,
            'ya-map': Map,
            'list': List
        },
        data() {
            return {
                message: 'Welcome to Vue.js'
            }
        }
    }
</script>
